const types = {
	SET_BRIGADES: 'SET_BRIGADES',
	SET_BRIGADES_LOADING: 'SET_BRIGADES_LOADING',
	SET_ERROR: 'SET_ERROR',
	DELETE_BRIGADE: 'DELETE_BRIGADE',
	GET_BRIGADES: 'GET_BRIGADES',
}

export default types